server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: quitstart
  boot:
    admin:
      client:
        url: http://localhost:19000/admin
#        username: admin
#        password: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:1234@localhost:8761/eureka
      
management:
  httpexchanges:
    recording:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
    prometheus:
      enabled: true  
    env:
      enabled: true
    busrefresh:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    enable:
      hikaricp: true
  
