spring:
  application:
    name: transfer
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:9393
    

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:1234@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
