mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: transfer 
  boot:
    admin:
      client:
        url: http://localhost:19000/adminPage

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:1234@localhost:8761/eureka

management:
  httpexchanges:
    recording:
      enabled: true
  endpoints:
    web:
      exposure:
#        include: "*"
        include: health, info, metrics, prometheus, busrefresh
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
    prometheus:
      enabled: true  
    env:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    enable:
      hikaricp: true
